/**
 * Created by Hello on 2016/9/28.
 */
var cityData = [{
    "value": 1,
    "text": "北京市",
    "children": [{
        "value": 415,
        "text": "东城区"
    }, {
        "value": 416,
        "text": "西城区"
    }, {
        "value": 417,
        "text": "崇文区"
    }, {
        "value": 418,
        "text": "宣武区"
    }, {
        "value": 419,
        "text": "朝阳区"
    }, {
        "value": 420,
        "text": "丰台区"
    }, {
        "value": 421,
        "text": "石景山区"
    }, {
        "value": 422,
        "text": "海淀区"
    }, {
        "value": 423,
        "text": "门头沟区"
    }, {
        "value": 424,
        "text": "房山区"
    }, {
        "value": 425,
        "text": "通州区"
    }, {
        "value": 426,
        "text": "顺义区"
    }, {
        "value": 427,
        "text": "昌平区"
    }, {
        "value": 428,
        "text": "大兴区"
    }, {
        "value": 429,
        "text": "怀柔区"
    }, {
        "value": 430,
        "text": "平谷区"
    }, {
        "value": 431,
        "text": "延庆县"
    }, {
        "value": 432,
        "text": "密云县"
    }]
}, {
    "value": 2,
    "text": "上海市",
    "children": [{
        "value": 449,
        "text": "黄浦区"
    }, {
        "value": 450,
        "text": "浦东新区"
    }, {
        "value": 451,
        "text": "徐汇区"
    }, {
        "value": 452,
        "text": "长宁区"
    }, {
        "value": 453,
        "text": "静安区"
    }, {
        "value": 454,
        "text": "普陀区"
    }, {
        "value": 455,
        "text": "闸北区"
    }, {
        "value": 456,
        "text": "虹口区"
    }, {
        "value": 457,
        "text": "杨浦区"
    }, {
        "value": 458,
        "text": "闵行区"
    }, {
        "value": 459,
        "text": "宝山区"
    }, {
        "value": 460,
        "text": "嘉定区"
    }, {
        "value": 461,
        "text": "金山区"
    }, {
        "value": 462,
        "text": "松江区"
    }, {
        "value": 463,
        "text": "青浦区"
    }, {
        "value": 464,
        "text": "奉贤区"
    }, {
        "value": 465,
        "text": "崇明县"
    }]
}, {
    "value": 3,
    "text": "天津市",
    "children": [{
        "value": 433,
        "text": "和平区"
    }, {
        "value": 434,
        "text": "河西区"
    }, {
        "value": 435,
        "text": "南开区"
    }, {
        "value": 436,
        "text": "河东区"
    }, {
        "value": 437,
        "text": "河北区"
    }, {
        "value": 438,
        "text": "红桥区"
    }, {
        "value": 439,
        "text": "东丽区"
    }, {
        "value": 440,
        "text": "津南区"
    }, {
        "value": 441,
        "text": "西青区"
    }, {
        "value": 442,
        "text": "北辰区"
    }, {
        "value": 443,
        "text": "滨海新区"
    }, {
        "value": 444,
        "text": "武清区"
    }, {
        "value": 445,
        "text": "宝坻区"
    }, {
        "value": 446,
        "text": "蓟县"
    }, {
        "value": 447,
        "text": "宁河县"
    }, {
        "value": 448,
        "text": "静海县"
    }]
}, {
    "value": 4,
    "text": "重庆市",
    "children": [{
        "value": 466,
        "text": "万州区"
    }, {
        "value": 467,
        "text": "黔江区"
    }, {
        "value": 468,
        "text": "涪陵区"
    }, {
        "value": 469,
        "text": "渝中区"
    }, {
        "value": 470,
        "text": "大渡口区"
    }, {
        "value": 471,
        "text": "江北区"
    }, {
        "value": 472,
        "text": "沙坪坝区"
    }, {
        "value": 473,
        "text": "九龙坡区"
    }, {
        "value": 474,
        "text": "南岸区"
    }, {
        "value": 475,
        "text": "北碚区"
    }, {
        "value": 476,
        "text": "渝北区"
    }, {
        "value": 477,
        "text": "巴南区"
    }, {
        "value": 478,
        "text": "长寿区"
    }, {
        "value": 479,
        "text": "江津区"
    }, {
        "value": 480,
        "text": "合川区"
    }, {
        "value": 481,
        "text": "永川区"
    }, {
        "value": 482,
        "text": "南川区"
    }, {
        "value": 483,
        "text": "綦江区"
    }, {
        "value": 484,
        "text": "大足区"
    }, {
        "value": 485,
        "text": "铜梁区"
    }, {
        "value": 486,
        "text": "璧山区"
    }, {
        "value": 487,
        "text": "其他"
    }]
}, {
    "value": 5,
    "text": "河北省",
    "children": [{
        "value": 35,
        "text": "石家庄市"
    }, {
        "value": 36,
        "text": "唐山市"
    }, {
        "value": 37,
        "text": "秦皇岛市"
    }, {
        "value": 38,
        "text": "邯郸市"
    }, {
        "value": 39,
        "text": "邢台市"
    }, {
        "value": 40,
        "text": "保定市"
    }, {
        "value": 41,
        "text": "张家口市"
    }, {
        "value": 42,
        "text": "承德市"
    }, {
        "value": 43,
        "text": "沧州市"
    }, {
        "value": 44,
        "text": "廊坊市"
    }, {
        "value": 45,
        "text": "衡水市"
    }]
}, {
    "value": 6,
    "text": "山西省",
    "children": [{
        "value": 46,
        "text": "太原市"
    }, {
        "value": 47,
        "text": "大同市"
    }, {
        "value": 48,
        "text": "阳泉市"
    }, {
        "value": 49,
        "text": "长治市"
    }, {
        "value": 50,
        "text": "晋城市"
    }, {
        "value": 51,
        "text": "朔州市"
    }, {
        "value": 52,
        "text": "晋中市"
    }, {
        "value": 53,
        "text": "运城市"
    }, {
        "value": 54,
        "text": "忻州市"
    }, {
        "value": 55,
        "text": "临汾市"
    }, {
        "value": 56,
        "text": "吕梁市"
    }]
}, {
    "value": 7,
    "text": "内蒙古自治区",
    "children": [{
        "value": 57,
        "text": "呼和浩特市"
    }, {
        "value": 58,
        "text": "包头市"
    }, {
        "value": 59,
        "text": "乌海市"
    }, {
        "value": 60,
        "text": "赤峰市"
    }, {
        "value": 61,
        "text": "通辽市"
    }, {
        "value": 62,
        "text": "鄂尔多斯市"
    }, {
        "value": 63,
        "text": "呼伦贝尔市"
    }, {
        "value": 64,
        "text": "巴彦淖尔市"
    }, {
        "value": 65,
        "text": "乌兰察布市"
    }, {
        "value": 66,
        "text": "兴安盟"
    }, {
        "value": 67,
        "text": "锡林郭勒盟"
    }, {
        "value": 68,
        "text": "阿拉善盟"
    }]
}, {
    "value": 8,
    "text": "辽宁省",
    "children": [{
        "value": 69,
        "text": "沈阳市"
    }, {
        "value": 70,
        "text": "大连市"
    }, {
        "value": 71,
        "text": "鞍山市"
    }, {
        "value": 72,
        "text": "抚顺市"
    }, {
        "value": 73,
        "text": "本溪市"
    }, {
        "value": 74,
        "text": "丹东市"
    }, {
        "value": 75,
        "text": "锦州市"
    }, {
        "value": 76,
        "text": "营口市"
    }, {
        "value": 77,
        "text": "阜新市"
    }, {
        "value": 78,
        "text": "辽阳市"
    }, {
        "value": 79,
        "text": "盘锦市"
    }, {
        "value": 80,
        "text": "铁岭市"
    }, {
        "value": 81,
        "text": "朝阳市"
    }, {
        "value": 82,
        "text": "葫芦岛市"
    }]
}, {
    "value": 9,
    "text": "吉林省",
    "children": [{
        "value": 83,
        "text": "长春市"
    }, {
        "value": 84,
        "text": "吉林市"
    }, {
        "value": 85,
        "text": "四平市"
    }, {
        "value": 86,
        "text": "辽源市"
    }, {
        "value": 87,
        "text": "通化市"
    }, {
        "value": 88,
        "text": "白山市"
    }, {
        "value": 89,
        "text": "松原市"
    }, {
        "value": 90,
        "text": "白城市"
    }, {
        "value": 91,
        "text": "延边朝鲜族自治州"
    }]
}, {
    "value": 10,
    "text": "黑龙江省",
    "children": [{
        "value": 92,
        "text": "哈尔滨市"
    }, {
        "value": 93,
        "text": "齐齐哈尔市"
    }, {
        "value": 94,
        "text": "鸡西市"
    }, {
        "value": 95,
        "text": "鹤岗市"
    }, {
        "value": 96,
        "text": "双鸭山市"
    }, {
        "value": 97,
        "text": "大庆市"
    }, {
        "value": 98,
        "text": "伊春市"
    }, {
        "value": 99,
        "text": "佳木斯市"
    }, {
        "value": 100,
        "text": "七台河市"
    }, {
        "value": 101,
        "text": "牡丹江市"
    }, {
        "value": 102,
        "text": "黑河市"
    }, {
        "value": 103,
        "text": "绥化市"
    }, {
        "value": 104,
        "text": "大兴安岭地区"
    }]
}, {
    "value": 11,
    "text": "江苏省",
    "children": [{
        "value": 105,
        "text": "南京市"
    }, {
        "value": 106,
        "text": "无锡市"
    }, {
        "value": 107,
        "text": "徐州市"
    }, {
        "value": 108,
        "text": "常州市"
    }, {
        "value": 109,
        "text": "苏州市"
    }, {
        "value": 110,
        "text": "南通市"
    }, {
        "value": 111,
        "text": "连云港市"
    }, {
        "value": 112,
        "text": "淮安市"
    }, {
        "value": 113,
        "text": "盐城市"
    }, {
        "value": 114,
        "text": "扬州市"
    }, {
        "value": 115,
        "text": "镇江市"
    }, {
        "value": 116,
        "text": "泰州市"
    }, {
        "value": 117,
        "text": "宿迁市"
    }]
}, {
    "value": 12,
    "text": "浙江省",
    "children": [{
        "value": 118,
        "text": "杭州市"
    }, {
        "value": 119,
        "text": "宁波市"
    }, {
        "value": 120,
        "text": "温州市"
    }, {
        "value": 121,
        "text": "嘉兴市"
    }, {
        "value": 122,
        "text": "湖州市"
    }, {
        "value": 123,
        "text": "绍兴市"
    }, {
        "value": 124,
        "text": "金华市"
    }, {
        "value": 125,
        "text": "衢州市"
    }, {
        "value": 126,
        "text": "舟山市"
    }, {
        "value": 127,
        "text": "台州市"
    }, {
        "value": 128,
        "text": "丽水市"
    }]
}, {
    "value": 13,
    "text": "安徽省",
    "children": [{
        "value": 129,
        "text": "合肥市"
    }, {
        "value": 130,
        "text": "芜湖市"
    }, {
        "value": 131,
        "text": "蚌埠市"
    }, {
        "value": 132,
        "text": "淮南市"
    }, {
        "value": 133,
        "text": "马鞍山市"
    }, {
        "value": 134,
        "text": "淮北市"
    }, {
        "value": 135,
        "text": "铜陵市"
    }, {
        "value": 136,
        "text": "安庆市"
    }, {
        "value": 137,
        "text": "黄山市"
    }, {
        "value": 138,
        "text": "滁州市"
    }, {
        "value": 139,
        "text": "阜阳市"
    }, {
        "value": 140,
        "text": "宿州市"
    }, {
        "value": 141,
        "text": "巢湖市"
    }, {
        "value": 142,
        "text": "六安市"
    }, {
        "value": 143,
        "text": "亳州市"
    }, {
        "value": 144,
        "text": "池州市"
    }, {
        "value": 145,
        "text": "宣城市"
    }]
}, {
    "value": 14,
    "text": "福建省",
    "children": [{
        "value": 146,
        "text": "福州市"
    }, {
        "value": 147,
        "text": "厦门市"
    }, {
        "value": 148,
        "text": "莆田市"
    }, {
        "value": 149,
        "text": "三明市"
    }, {
        "value": 150,
        "text": "泉州市"
    }, {
        "value": 151,
        "text": "漳州市"
    }, {
        "value": 152,
        "text": "南平市"
    }, {
        "value": 153,
        "text": "龙岩市"
    }, {
        "value": 154,
        "text": "宁德市"
    }]
}, {
    "value": 15,
    "text": "江西省",
    "children": [{
        "value": 155,
        "text": "南昌市"
    }, {
        "value": 156,
        "text": "景德镇市"
    }, {
        "value": 157,
        "text": "萍乡市"
    }, {
        "value": 158,
        "text": "九江市"
    }, {
        "value": 159,
        "text": "新余市"
    }, {
        "value": 160,
        "text": "鹰潭市"
    }, {
        "value": 161,
        "text": "赣州市"
    }, {
        "value": 162,
        "text": "吉安市"
    }, {
        "value": 163,
        "text": "宜春市"
    }, {
        "value": 164,
        "text": "抚州市"
    }, {
        "value": 165,
        "text": "上饶市"
    }]
}, {
    "value": 16,
    "text": "山东省",
    "children": [{
        "value": 166,
        "text": "济南市"
    }, {
        "value": 167,
        "text": "青岛市"
    }, {
        "value": 168,
        "text": "淄博市"
    }, {
        "value": 169,
        "text": "枣庄市"
    }, {
        "value": 170,
        "text": "东营市"
    }, {
        "value": 171,
        "text": "烟台市"
    }, {
        "value": 172,
        "text": "潍坊市"
    }, {
        "value": 173,
        "text": "济宁市"
    }, {
        "value": 174,
        "text": "泰安市"
    }, {
        "value": 175,
        "text": "威海市"
    }, {
        "value": 176,
        "text": "日照市"
    }, {
        "value": 177,
        "text": "莱芜市"
    }, {
        "value": 178,
        "text": "临沂市"
    }, {
        "value": 179,
        "text": "德州市"
    }, {
        "value": 180,
        "text": "聊城市"
    }, {
        "value": 181,
        "text": "滨州市"
    }, {
        "value": 182,
        "text": "荷泽市"
    }]
}, {
    "value": 17,
    "text": "河南省",
    "children": [{
        "value": 183,
        "text": "郑州市"
    }, {
        "value": 184,
        "text": "开封市"
    }, {
        "value": 185,
        "text": "洛阳市"
    }, {
        "value": 186,
        "text": "平顶山市"
    }, {
        "value": 187,
        "text": "安阳市"
    }, {
        "value": 188,
        "text": "鹤壁市"
    }, {
        "value": 189,
        "text": "新乡市"
    }, {
        "value": 190,
        "text": "焦作市"
    }, {
        "value": 191,
        "text": "濮阳市"
    }, {
        "value": 192,
        "text": "许昌市"
    }, {
        "value": 193,
        "text": "漯河市"
    }, {
        "value": 194,
        "text": "三门峡市"
    }, {
        "value": 195,
        "text": "南阳市"
    }, {
        "value": 196,
        "text": "商丘市"
    }, {
        "value": 197,
        "text": "信阳市"
    }, {
        "value": 198,
        "text": "周口市"
    }, {
        "value": 199,
        "text": "驻马店市"
    }, {
        "value": 200,
        "text": "济源市"
    }]
}, {
    "value": 18,
    "text": "湖北省",
    "children": [{
        "value": 201,
        "text": "武汉市"
    }, {
        "value": 202,
        "text": "黄石市"
    }, {
        "value": 203,
        "text": "十堰市"
    }, {
        "value": 204,
        "text": "宜昌市"
    }, {
        "value": 205,
        "text": "襄阳市"
    }, {
        "value": 206,
        "text": "鄂州市"
    }, {
        "value": 207,
        "text": "荆门市"
    }, {
        "value": 208,
        "text": "孝感市"
    }, {
        "value": 209,
        "text": "荆州市"
    }, {
        "value": 210,
        "text": "黄冈市"
    }, {
        "value": 211,
        "text": "咸宁市"
    }, {
        "value": 212,
        "text": "随州市"
    }, {
        "value": 213,
        "text": "恩施土家族苗族自治州"
    }, {
        "value": 214,
        "text": "仙桃市"
    }, {
        "value": 215,
        "text": "潜江市"
    }, {
        "value": 216,
        "text": "天门市"
    }, {
        "value": 217,
        "text": "神农架林区"
    }]
}, {
    "value": 19,
    "text": "湖南省",
    "children": [{
        "value": 218,
        "text": "长沙市"
    }, {
        "value": 219,
        "text": "株洲市"
    }, {
        "value": 220,
        "text": "湘潭市"
    }, {
        "value": 221,
        "text": "衡阳市"
    }, {
        "value": 222,
        "text": "邵阳市"
    }, {
        "value": 223,
        "text": "岳阳市"
    }, {
        "value": 224,
        "text": "常德市"
    }, {
        "value": 225,
        "text": "张家界市"
    }, {
        "value": 226,
        "text": "益阳市"
    }, {
        "value": 227,
        "text": "郴州市"
    }, {
        "value": 228,
        "text": "永州市"
    }, {
        "value": 229,
        "text": "怀化市"
    }, {
        "value": 230,
        "text": "娄底市"
    }, {
        "value": 231,
        "text": "湘西土家族苗族自治州"
    }]
}, {
    "value": 20,
    "text": "广东省",
    "children": [{
        "value": 232,
        "text": "广州市"
    }, {
        "value": 233,
        "text": "深圳市"
    }, {
        "value": 234,
        "text": "珠海市"
    }, {
        "value": 235,
        "text": "汕头市"
    }, {
        "value": 236,
        "text": "韶关市"
    }, {
        "value": 237,
        "text": "佛山市"
    }, {
        "value": 238,
        "text": "江门市"
    }, {
        "value": 239,
        "text": "湛江市"
    }, {
        "value": 240,
        "text": "茂名市"
    }, {
        "value": 241,
        "text": "肇庆市"
    }, {
        "value": 242,
        "text": "惠州市"
    }, {
        "value": 243,
        "text": "梅州市"
    }, {
        "value": 244,
        "text": "汕尾市"
    }, {
        "value": 245,
        "text": "河源市"
    }, {
        "value": 246,
        "text": "阳江市"
    }, {
        "value": 247,
        "text": "清远市"
    }, {
        "value": 248,
        "text": "东莞市"
    }, {
        "value": 249,
        "text": "中山市"
    }, {
        "value": 250,
        "text": "潮州市"
    }, {
        "value": 251,
        "text": "揭阳市"
    }, {
        "value": 252,
        "text": "云浮市"
    }]
}, {
    "value": 21,
    "text": "广西壮族自治区",
    "children": [{
        "value": 253,
        "text": "南宁市"
    }, {
        "value": 254,
        "text": "柳州市"
    }, {
        "value": 255,
        "text": "桂林市"
    }, {
        "value": 256,
        "text": "梧州市"
    }, {
        "value": 257,
        "text": "北海市"
    }, {
        "value": 258,
        "text": "防城港市"
    }, {
        "value": 259,
        "text": "钦州市"
    }, {
        "value": 260,
        "text": "贵港市"
    }, {
        "value": 261,
        "text": "玉林市"
    }, {
        "value": 262,
        "text": "百色市"
    }, {
        "value": 263,
        "text": "贺州市"
    }, {
        "value": 264,
        "text": "河池市"
    }, {
        "value": 265,
        "text": "来宾市"
    }, {
        "value": 266,
        "text": "崇左市"
    }]
}, {
    "value": 22,
    "text": "海南省",
    "children": [{
        "value": 267,
        "text": "海口市"
    }, {
        "value": 268,
        "text": "三亚市"
    }, {
        "value": 269,
        "text": "五指山市"
    }, {
        "value": 270,
        "text": "琼海市"
    }, {
        "value": 271,
        "text": "儋州市"
    }, {
        "value": 272,
        "text": "文昌市"
    }, {
        "value": 273,
        "text": "万宁市"
    }, {
        "value": 274,
        "text": "东方市"
    }, {
        "value": 275,
        "text": "澄迈县"
    }, {
        "value": 276,
        "text": "定安县"
    }, {
        "value": 277,
        "text": "屯昌县"
    }, {
        "value": 278,
        "text": "临高县"
    }, {
        "value": 279,
        "text": "白沙黎族自治县"
    }, {
        "value": 280,
        "text": "昌江黎族自治县"
    }, {
        "value": 281,
        "text": "乐东黎族自治县"
    }, {
        "value": 282,
        "text": "陵水黎族自治县"
    }, {
        "value": 283,
        "text": "保亭黎族苗族自治县"
    }, {
        "value": 284,
        "text": "琼中黎族苗族自治县"
    }]
}, {
    "value": 23,
    "text": "四川省",
    "children": [{
        "value": 285,
        "text": "成都市"
    }, {
        "value": 286,
        "text": "自贡市"
    }, {
        "value": 287,
        "text": "攀枝花市"
    }, {
        "value": 288,
        "text": "泸州市"
    }, {
        "value": 289,
        "text": "德阳市"
    }, {
        "value": 290,
        "text": "绵阳市"
    }, {
        "value": 291,
        "text": "广元市"
    }, {
        "value": 292,
        "text": "遂宁市"
    }, {
        "value": 293,
        "text": "内江市"
    }, {
        "value": 294,
        "text": "乐山市"
    }, {
        "value": 295,
        "text": "南充市"
    }, {
        "value": 296,
        "text": "眉山市"
    }, {
        "value": 297,
        "text": "宜宾市"
    }, {
        "value": 298,
        "text": "广安市"
    }, {
        "value": 299,
        "text": "达州市"
    }, {
        "value": 300,
        "text": "雅安市"
    }, {
        "value": 301,
        "text": "巴中市"
    }, {
        "value": 302,
        "text": "资阳市"
    }, {
        "value": 303,
        "text": "阿坝藏族羌族自治州"
    }, {
        "value": 304,
        "text": "甘孜藏族自治州"
    }, {
        "value": 305,
        "text": "凉山彝族自治州"
    }]
}, {
    "value": 24,
    "text": "贵州省",
    "children": [{
        "value": 306,
        "text": "贵阳市"
    }, {
        "value": 307,
        "text": "六盘水市"
    }, {
        "value": 308,
        "text": "遵义市"
    }, {
        "value": 309,
        "text": "安顺市"
    }, {
        "value": 310,
        "text": "铜仁地区"
    }, {
        "value": 311,
        "text": "毕节地区"
    }, {
        "value": 312,
        "text": "黔西南布依族苗族自治州"
    }, {
        "value": 313,
        "text": "黔东南苗族侗族自治州"
    }, {
        "value": 314,
        "text": "黔南布依族苗族自治州"
    }, {
        "value": 499,
        "text": "兴义市"
    }]
}, {
    "value": 25,
    "text": "云南省",
    "children": [{
        "value": 315,
        "text": "昆明市"
    }, {
        "value": 316,
        "text": "曲靖市"
    }, {
        "value": 317,
        "text": "玉溪市"
    }, {
        "value": 318,
        "text": "保山市"
    }, {
        "value": 319,
        "text": "昭通市"
    }, {
        "value": 320,
        "text": "丽江市"
    }, {
        "value": 321,
        "text": "普洱市"
    }, {
        "value": 322,
        "text": "临沧市"
    }, {
        "value": 323,
        "text": "楚雄彝族自治州"
    }, {
        "value": 324,
        "text": "红河哈尼族彝族自治州"
    }, {
        "value": 325,
        "text": "文山壮族苗族自治州"
    }, {
        "value": 326,
        "text": "西双版纳傣族自治州"
    }, {
        "value": 327,
        "text": "大理白族自治州"
    }, {
        "value": 328,
        "text": "德宏傣族景颇族自治州"
    }, {
        "value": 329,
        "text": "怒江傈僳族自治州"
    }, {
        "value": 330,
        "text": "迪庆藏族自治州"
    }]
}, {
    "value": 26,
    "text": "西藏自治区",
    "children": [{
        "value": 331,
        "text": "拉萨市"
    }, {
        "value": 332,
        "text": "昌都地区"
    }, {
        "value": 333,
        "text": "林芝地区"
    }, {
        "value": 334,
        "text": "山南地区"
    }, {
        "value": 335,
        "text": "日喀则地区"
    }, {
        "value": 336,
        "text": "那曲地区"
    }, {
        "value": 337,
        "text": "阿里地区"
    }]
}, {
    "value": 27,
    "text": "陕西省",
    "children": [{
        "value": 338,
        "text": "西安市"
    }, {
        "value": 339,
        "text": "铜川市"
    }, {
        "value": 340,
        "text": "宝鸡市"
    }, {
        "value": 341,
        "text": "咸阳市"
    }, {
        "value": 342,
        "text": "渭南市"
    }, {
        "value": 343,
        "text": "延安市"
    }, {
        "value": 344,
        "text": "汉中市"
    }, {
        "value": 345,
        "text": "榆林市"
    }, {
        "value": 346,
        "text": "安康市"
    }, {
        "value": 347,
        "text": "商洛市"
    }]
}, {
    "value": 28,
    "text": "甘肃省",
    "children": [{
        "value": 348,
        "text": "兰州市"
    }, {
        "value": 349,
        "text": "嘉峪关市"
    }, {
        "value": 350,
        "text": "金昌市"
    }, {
        "value": 351,
        "text": "白银市"
    }, {
        "value": 352,
        "text": "天水市"
    }, {
        "value": 353,
        "text": "武威市"
    }, {
        "value": 354,
        "text": "张掖市"
    }, {
        "value": 355,
        "text": "平凉市"
    }, {
        "value": 356,
        "text": "酒泉市"
    }, {
        "value": 357,
        "text": "庆阳市"
    }, {
        "value": 358,
        "text": "定西市"
    }, {
        "value": 359,
        "text": "陇南市"
    }, {
        "value": 360,
        "text": "临夏回族自治州"
    }, {
        "value": 361,
        "text": "甘南藏族自治州"
    }]
}, {
    "value": 29,
    "text": "青海省",
    "children": [{
        "value": 362,
        "text": "西宁市"
    }, {
        "value": 363,
        "text": "海东地区"
    }, {
        "value": 364,
        "text": "海北藏族自治州"
    }, {
        "value": 365,
        "text": "黄南藏族自治州"
    }, {
        "value": 366,
        "text": "海南藏族自治州"
    }, {
        "value": 367,
        "text": "果洛藏族自治州"
    }, {
        "value": 368,
        "text": "玉树藏族自治州"
    }, {
        "value": 369,
        "text": "海西蒙古族藏族自治州"
    }]
}, {
    "value": 30,
    "text": "宁夏回族自治区",
    "children": [{
        "value": 370,
        "text": "银川市"
    }, {
        "value": 371,
        "text": "石嘴山市"
    }, {
        "value": 372,
        "text": "吴忠市"
    }, {
        "value": 373,
        "text": "固原市"
    }, {
        "value": 374,
        "text": "中卫市"
    }]
}, {
    "value": 31,
    "text": "新疆维吾尔自治区",
    "children": [{
        "value": 375,
        "text": "乌鲁木齐市"
    }, {
        "value": 376,
        "text": "克拉玛依市"
    }, {
        "value": 377,
        "text": "吐鲁番地区"
    }, {
        "value": 378,
        "text": "哈密地区"
    }, {
        "value": 379,
        "text": "昌吉回族自治州"
    }, {
        "value": 380,
        "text": "博尔塔拉蒙古自治州"
    }, {
        "value": 381,
        "text": "巴音郭楞蒙古自治州"
    }, {
        "value": 382,
        "text": "阿克苏地区"
    }, {
        "value": 383,
        "text": "克孜勒苏柯尔克孜自治州"
    }, {
        "value": 384,
        "text": "喀什地区"
    }, {
        "value": 385,
        "text": "和田地区"
    }, {
        "value": 386,
        "text": "伊犁哈萨克自治州"
    }, {
        "value": 387,
        "text": "塔城地区"
    }, {
        "value": 388,
        "text": "阿勒泰地区"
    }, {
        "value": 389,
        "text": "石河子市"
    }, {
        "value": 390,
        "text": "阿拉尔市"
    }, {
        "value": 391,
        "text": "图木舒克市"
    }, {
        "value": 392,
        "text": "五家渠市"
    }]
}, {
    "value": 32,
    "text": "台湾省",
    "children": [{
        "value": 393,
        "text": "台北市"
    }, {
        "value": 394,
        "text": "高雄市"
    }, {
        "value": 395,
        "text": "基隆市"
    }, {
        "value": 396,
        "text": "台中市"
    }, {
        "value": 397,
        "text": "台南市"
    }, {
        "value": 398,
        "text": "新竹市"
    }, {
        "value": 399,
        "text": "嘉义市"
    }, {
        "value": 400,
        "text": "台北县"
    }, {
        "value": 401,
        "text": "宜兰县"
    }, {
        "value": 402,
        "text": "桃园县"
    }, {
        "value": 403,
        "text": "新竹县"
    }, {
        "value": 404,
        "text": "苗栗县"
    }, {
        "value": 405,
        "text": "台中县"
    }, {
        "value": 406,
        "text": "彰化县"
    }, {
        "value": 407,
        "text": "南投县"
    }, {
        "value": 408,
        "text": "云林县"
    }, {
        "value": 409,
        "text": "嘉义县"
    }, {
        "value": 410,
        "text": "台南县"
    }, {
        "value": 411,
        "text": "高雄县"
    }, {
        "value": 412,
        "text": "屏东县"
    }, {
        "value": 413,
        "text": "台东县"
    }, {
        "value": 414,
        "text": "花莲县"
    }]
}, {
    "value": 33,
    "text": "香港特别行政区",
    "children": [{
        "value": 489,
        "text": "港岛区"
    }, {
        "value": 490,
        "text": "九龙区"
    }, {
        "value": 491,
        "text": "新界及离岛区"
    }]
}, {
    "value": 34,
    "text": "澳门特别行政区",
    "children": [{
        "value": 492,
        "text": "澳门"
    }]
}]